name: Build
on:
  push: {}
  pull_request: {}
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ '14', '16' ]
    name: Node ${{ matrix.node }} sample
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          cache: yarn
      - name: Installing
        run: yarn install --frozen-lockfile
      - name: Linting
        run: yarn lint
      - name: Testing
        run: yarn workspaces run test
        